-- DDL 테이블 생성 수정 삭제
-- 테이블 생성
CREATE TABLE 테스트 (
    문자열 VARCHAR2(100),
    숫자 NUMBER,
    날짜 DATE DEFAULT SYSDATE
);

-- 테이블 삭제
DROP TABLE 테스트;

DESC 테스트;
SELECT * FROM 테스트;

-- 데이터 입력
INSERT INTO 테스트 VALUES ('HTML', 5, '2021/10/08');
INSERT INTO 테스트 VALUES ('CSS', 3, SYSDATE);
INSERT INTO 테스트(문자열, 숫자) VALUES ('자바', 7);

-- 기존 테이블 복사해서 만드는 방법
-- 열 구조만 복사
CREATE TABLE EMP_TEMP
AS
SELECT * FROM EMPLOYEES WHERE 1 <> 1;

SELECT * FROM EMP_TEMP;

DESC EMP_TEMP;

--80번 부서의 직원들만 따로 테이블 생성
CREATE TABLE EMP80
AS
SELECT EMPLOYEE_ID 직원번호, LAST_NAME 이름, SALARY 월급, SALARY*12 연봉, HIRE_DATE 고용일
FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;

DESC EMP80;

SELECT * FROM EMP80;

-- 예제
CREATE TABLE stmans
AS
SELECT employee_id ID, job_id JOB, salary SAL
FROM EMPLOYEES WHERE JOB_ID = 'ST_MAN';

SELECT * FROM stmans;