-- 연습문제 1
SELECT empno, ENAME, sal
FROM EMP
WHERE DEPTNO = 10;

-- 연습문제 2
SELECT ENAME, hiredate, deptno
FROM EMP
WHERE EMPNO = 7369;

-- 연습문제 3
SELECT *
FROM EMP
WHERE ENAME = 'ALLEN';

-- 연습문제 4
SELECT ENAME, DEPTNO, sal
FROM EMP
WHERE hiredate = '81/02/20';

-- 연습문제 5
SELECT *
FROM EMP
WHERE JOB NOT LIKE 'MANAGER'; -- JOB <> 'MANAGER'

-- 연습문제 6
SELECT *
FROM EMP
WHERE hiredate >= '81/04/02';

-- 연습문제 7
SELECT ENAME, SAL, DEPTNO
FROM EMP
WHERE sal >= 800;

-- 연습문제 8
SELECT *
FROM EMP
WHERE deptno >= 20;

-- 연습문제 9
SELECT *
FROM EMP
WHERE ENAME > 'L%';

-- 연습문제 10
SELECT *
FROM EMP
WHERE hiredate < '81/12/09';

-- 연습문제 11
SELECT empno, ENAME
FROM EMP
WHERE EMPNO <= 7698;

-- 연습문제 12
SELECT ename, SAL, deptno
FROM EMP
WHERE HIREDATE BETWEEN '81/04/02' AND '82/12/09';

-- 연습문제 13
SELECT ENAME, JOB, sal
FROM EMP
WHERE SAL > 1600 AND SAL < 3000;

-- 연습문제 14
SELECT *
FROM EMP
WHERE EMPNO NOT BETWEEN 7654 AND 7782;

-- 연습문제 15
SELECT *
FROM EMP
WHERE ENAME BETWEEN 'B' AND 'J';

-- 연습문제 16
SELECT *
FROM EMP
WHERE HIREDATE NOT BETWEEN '81/01/01' AND '81/12/31';

SELECT *
FROM EMP
WHERE TO_CHAR(HIREDATE, 'YYYY') <> '1981';

-- 연습문제 17
SELECT *
FROM emp
WHERE job = 'MANAGER' OR JOB = 'SALESMAN';

SELECT *
FROM emp
WHERE JOB IN ('MANAGER', 'SALESMAN');

-- 연습문제 18
SELECT *
FROM emp
WHERE deptno <> 20 AND DEPTNO <> 30;

SELECT *
FROM emp
WHERE DEPTNO NOT IN (20, 30);

-- 연습문제 19
SELECT EMPNO, ENAME, hiredate, deptno
FROM emp
WHERE ENAME LIKE 'S%';

-- 연습문제 20
SELECT *
FROM EMP
WHERE HIREDATE BETWEEN '81/01/01' AND '81/12/31';

-- 연습문제 21
SELECT *
FROM EMP
WHERE ENAME LIKE '%S%';

-- 연습문제 22
SELECT *
FROM EMP
WHERE ENAME LIKE 'M____N';

-- 연습문제 23
SELECT *
FROM EMP
WHERE ENAME LIKE '_A%';

-- 연습문제 24
SELECT *
FROM EMP
WHERE comm IS NULL;

-- 연습문제 25
SELECT *
FROM EMP
WHERE COMM IS NOT NULL;

-- 연습문제 26
SELECT ENAME, DEPTNO, SAL
FROM EMP
WHERE deptno = 30 AND SAL >= 1500;

-- 연습문제 27
SELECT EMPNO, ENAME, DEPTNO
FROM EMP
WHERE ENAME LIKE 'K%' OR DEPTNO = 30;

-- 연습문제 28
SELECT *
FROM EMP
WHERE SAL >= 1500 AND DEPTNO = 30 AND JOB  = 'MANAGER';

-- 연습문제 29
SELECT *
FROM EMP
WHERE deptno = 30
ORDER BY EMPNO;

-- 연습문제 30
SELECT *
FROM EMP
ORDER BY SAL DESC;

-- 연습문제 31
SELECT *
FROM EMP
ORDER BY deptno ASC, SAL DESC;

-- 연습문제 32
SELECT DEPTNO, ENAME, SAL
FROM emp
ORDER BY deptno DESC, ENAME ASC, SAL DESC;

-- 연습문제 33
SELECT ename, SAL, ROUND(SAL*0.13) BONUS, DEPTNO
FROM EMP
WHERE deptno = 10;

-- 연습문제 34
SELECT ENAME, SAL, NVL(COMM, 0), SAL+NVL(COMM, 0) TOTAL
FROM EMP
ORDER BY TOTAL DESC;

-- 연습문제 35
SELECT ENAME, SAL, TO_CHAR(ROUND(SAL*0.15, 1), '$9,999.9') 회비
FROM EMP
WHERE SAL BETWEEN 1500 AND 3000;

-- 연습문제 36
SELECT DNAME, COUNT(E.EMPNO)
FROM emp E JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
HAVING COUNT(E.EMPNO) > 5;

-- 연습문제 37
SELECT JOB, SAL+NVL(COMM, 0) 급여합계
FROM EMP
GROUP BY JOB
HAVING SAL+NVL(COMM, 0) > 5000; -- 풀이 참고

-- 연습문제 38
SELECT
FROM EMP; -- 풀이 참고


-- 연습문제 39
SELECT DEPTNO, COUNT(SAL) 사원수, COUNT(COMM) 커미션 받은 사원수
FROM EMP
GROUP BY DEPTNO; -- 풀이 참고

-- 연습문제 40
SELECT ENAME, DEPTNO,
    DECODE(DEPTNO, '10', '총무부',
                    '20', '개발부',
                    '30', '영업부') 부서명
FROM EMP;